learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
]

learning_logs/urls.py
# -*- coding:utf-8 -*-
# @Time: 2020/7/7 10:06
# @Author: Lj
# @File: urls.py

""" 定义 learning_logs 的 URL 模式 """

from django.conf.urls import url

from . import views

urlpatterns = [
    #主页
    url(r'^$', views.index, name='index'),
    #主题页
    url(r'^topics/$', views.topics, name='topics'),
    #具体主题
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    #添加新主题
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    #添加新条目
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    #编辑既有条目
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
# -*- coding:utf-8 -*-
# @Time: 2020/7/8 11:07
# @Author: Lj
# @File: urls.py

"""为应用程序users定义URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #登录界面
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    #注销
    url(r'^logout/$', views.logout_view, name='logout'),
    #注册
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.text

class Entry(models.Model):
    """某个主题的具体知识"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
# -*- coding:utf-8 -*-
# @Time: 2020/7/7 16:35
# @Author: Lj
# @File: forms.py

from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """学习笔记项目的主页"""
    return render(request, 'learning_logs/index.html')


@ login_required()
def topics(request):
    """显示某个用户的所有主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html', context)


@ login_required()
def topic(request, topic_id):
    """显示某个主题及其具体内容"""
    topic = Topic.objects.get(id=topic_id)
    #确认请求的主题属于当前用户
    if not _check_cur_owner(topic, request):
        raise Http404

    entries = topic.entry_set.order_by('-date_added')   #-号表示降序
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)


@ login_required()
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form':form}
    return render(request, 'learning_logs/new_topic.html', context)


@ login_required()
def new_entry(request, topic_id):
    """添加某个主题的新条目"""
    topic = Topic.objects.get(id=topic_id)

    if not _check_cur_owner(topic, request):
        raise Http404

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))
    context = {'topic':topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html', context)


@ login_required()
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if not _check_cur_owner(topic, request):
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)


def _check_cur_owner(topic, request) -> bool:
    """检测当前用户是否在操作别人的主题"""
    return topic.owner == request.user

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    """注销登录"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """用户注册账户"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            #让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username,
                                            password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>学习笔记</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
      <!-- Static navbar -->
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
            </button>
              <a class="navbar-brand" href="{% url 'learning_logs:index' %}">学习笔记</a>
          </div>

            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">主题</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated %}
                    <li><a>Hello,{{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">log out</a></li>
                  {% else %}
                    <li><a href="{% url 'users:register' %}">注册</a></li>
                    <li><a href="{% url 'users:login' %}">log in</a></li>
                  {% endif %}
                </ul>
            </div><!--/.nav-collapse -->

        </div>

      </nav>

      <div class="container">

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
      </div> <!-- /container -->

    </body>
</html>>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h2>
  <h3>编辑条目</h3>
{% endblock header %}

{% block content %}

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post"
        class="form">
      {% csrf_token %}
      {% bootstrap_form form%}

      {% buttons%}
      <button name="submit" class="btn btn-primary">保存修改</button>
      {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>记录你的学习过程</h1>
  </div>
{% endblock header%}

{% block content %}
  <h2>
      <a href="{% url 'users:register' %}">注册账户创建你自己的学习笔记，
          开启学习之旅吧！</a>
  </h2>
  <h2>
      学习笔记帮助你记录学习某个主题的知识
  </h2>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </h2>
  <h3>新建一个条目</h3>
{% endblock header %}

{% block content %}

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST"
            class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
      <button name="submit" class="btn btn-primary">添加条目</button>
      {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header%}
  <h3>新建一个主题</h3>
{% endblock header%}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method="post"
        class="form">

      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons%}
        <button name="submit" class="btn btn-primary">添加主题</button>
      {% endbuttons%}

  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header%}
  <h2>{{ topic }}</h2>
{% endblock header%}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新条目</a>
  </p>

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑条目</a>
        </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->

    {% empty %}
      还没有创建条目
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>主题</h1>
{% endblock header %}

{% block content %}

    <ul>
      {% for topic in topics %}
        <li>
          <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
          </h3>
        </li>
        {% empty %}
          <li>还没有创建主题</li>
        {% endfor %}
    </ul>
    <br />
    <h4>
      <a href="{% url 'learning_logs:new_topic' %}">创建新主题</a>
    </h4>

{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header%}
  <h3>用户登录</h3>
{% endblock header%}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

      <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h3>用户注册</h3>
{% endblock header %}

{% block content %}

  <form method="POST" action="{% url 'users:register' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
      <button name="submit" class="btn btn-primary">注册</button>
      {% endbuttons %}
      <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}